package com.traderz.anmolgupta.userData;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.*;
import com.traderz.anmolgupta.traderz.SocialAuth;

import java.util.Set;


/**
 * Created by anmolgupta on 03/04/15.
 */
@DynamoDBTable(tableName = "UserData")
public class UserData {

    private String firstName;
    private String lastName;
    private String email;
    private String location;
    private String country;
    private String language;
    private String facebookId;
    private String linkedInId;
    private String googlePlusId;
    private String twitterId;
    private String dob;
    private String imageUrl;
    private String gender;

    @DynamoDBAttribute(attributeName = "FirstName")
    public String getFirstName() {

        return firstName;
    }

    public void setFirstName( String firstName ) {

        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "LastName")
    public String getLastName() {

        return lastName;
    }

    public void setLastName( String lastName ) {

        this.lastName = lastName;
    }

    @DynamoDBHashKey(attributeName = "Email")
    public String getEmail() {

        return email;
    }

    public void setEmail( String email ) {

        this.email = email;
    }

    @DynamoDBAttribute(attributeName = "Location")
    public String getLocation() {

        return location;
    }

    public void setLocation( String location ) {

        this.location = location;
    }

    @DynamoDBAttribute(attributeName = "Country")
    public String getCountry() {

        return country;
    }

    public void setCountry( String country ) {

        this.country = country;
    }

    @DynamoDBAttribute(attributeName = "Language")
    public String getLanguage() {

        return language;
    }

    public void setLanguage( String language ) {

        this.language = language;
    }

    @DynamoDBAttribute(attributeName = "FacebookId")
    public String getFacebookId() {

        return facebookId;
    }

    public void setFacebookId( String facebookId ) {

        this.facebookId = facebookId;
    }

    @DynamoDBAttribute(attributeName = "LinkedInId")
    public String getLinkedInId() {

        return linkedInId;
    }

    public void setLinkedInId( String linkedInId ) {

        this.linkedInId = linkedInId;
    }

    @DynamoDBAttribute(attributeName = "GoogleId")
    public String getGooglePlusId() {

        return googlePlusId;
    }

    public void setGooglePlusId( String googlePlusId ) {

        this.googlePlusId = googlePlusId;
    }

    @DynamoDBAttribute(attributeName = "TwitterId")
    public String getTwitterId() {

        return twitterId;
    }

    public void setTwitterId( String twitterId ) {

        this.twitterId = twitterId;
    }

    @DynamoDBAttribute(attributeName = "DOB")
    public String getDob() {

        return dob;
    }

    public void setDob( String dob ) {

        this.dob = dob;
    }

    @DynamoDBAttribute(attributeName = "ImageURL")
    public String getImageUrl() {

        return imageUrl;
    }

    public void setImageUrl( String imageUrl ) {

        this.imageUrl = imageUrl;
    }


    @DynamoDBAttribute(attributeName = "Gender")
    public String getGender() {

        return gender;
    }

    public void setGender( String gender ) {

        this.gender = gender;
    }


//    private int price;
//    private String isbn;
//    private Boolean hardCover;

//    @DynamoDBHashKey(attributeName = "Id")
//    @DynamoDBAutoGeneratedKey
//    public String getTitle() {
//        return title;
//    }
//
//    public void setTitle(String title) {
//        this.title = title;
//    }
//
//    @DynamoDBRangeKey(attributeName = "Email")
    public UserData(){

    }

    public UserData(String email) {
        this.email = email;
    }

    public UserData(String email,
                    String country,
                    String dob,
                    String firstName,
                    String lastName,
                    String language,
                    String imageUrl,
                    String gender,
                    String location,
                    String socialId,
                    Social social) {

        this.email = email;
        this.country = country;
        this.firstName = firstName;
        this.language = language;
        this.lastName = lastName;
        this.dob = dob;
        this.imageUrl = imageUrl;
        this.gender = gender;
        this.location = location;
        setSocialId(social, socialId);

    }

    public void setSocialId(Social social, String socialId) {

        switch(social) {

            case FACEBOOK: setFacebookId(socialId);
                break;

            case TWITTER: setTwitterId(socialId);
                break;

            case LINKEDIN: setLinkedInId(socialId);
                break;

            case GOOGLE: setGooglePlusId(socialId);
                break;

            case GOOGLEPLUS: setGooglePlusId(socialId);
                break;

        }
    }
}
