package com.traderz.anmolgupta.userData;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

/**
 * Created by anmolgupta on 05/05/15.
 */
@DynamoDBTable(tableName = "UserKey")
public class UserKey {

    String email;
    Long timestamp;

    @DynamoDBHashKey(attributeName = "Email")
    public String getEmail() {

        return email;
    }

    public void setEmail( String email ) {

        this.email = email;
    }

    @DynamoDBIndexRangeKey(attributeName = "Timestamp")
    public Long getTimestamp() {

        return timestamp;
    }

    public void setTimestamp( Long timestamp ) {

        this.timestamp = timestamp;
    }

    @DynamoDBRangeKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {

        return id;
    }

    public void setId( String id ) {

        this.id = id;
    }

    String id;
}
