package com.traderz.anmolgupta.userData;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

/**
 * Created by anmolgupta on 19/04/15.
 */
@DynamoDBTable(tableName = "UserData1")
public class UserDataTest {

    String email;
    String id;
    String custom;
    String custom1;

    @DynamoDBHashKey(attributeName = "Email")
    public String getEmail() {

        return email;
    }

    public void setEmail( String email ) {

        this.email = email;
    }

    @DynamoDBIndexRangeKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {

        return id;
    }

    public void setId( String id ) {

        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "Custom")
    public String getCustom() {

        return custom;
    }

    public void setCustom( String custom ) {

        this.custom = custom;
    }

    @DynamoDBAttribute(attributeName = "Custom1")
    public String getCustom1() {

        return custom1;
    }

    public void setCustom1( String custom1 ) {

        this.custom1 = custom1;
    }
}
